### ISSUE TITLE
error

### ISSUE THREAD

**Issue by RacunaMatataIsLife** [johndelara1/instagram-sorteio#1]
Essa parte esta dando erro de elemento não encontrado

try:
            ff.find_element_by_xpath(
                '/html/body/div[2]/div/div/div/div[3]/button[2]').click()
            sleep(1)
            ff.find_element_by_xpath(
                '//*[@id="react-root"]/section/nav/div[2]/div/div/div[3]/div/div[3]/a').click()
        except:
            sleep(3)
            ff.find_element_by_xpath(
                '/html/body/div[2]/div/div/div/div[3]/button[2]').click()
            sleep(1)
            ff.find_element_by_xpath(
                '//*[@id="react-root"]/section/nav/div[2]/div/div/div[3]/div/div[3]/a').click()

porem não sei o que esta acontecendo, e onde esta esses elementos na nova interface do instagram para corrigir, poderia me informar?

**Comment by johndelara1** [comment]
Pode click com botão direito onde você quer que ele click, vai em inspecionar, depois pode copiar o XPath correspondente
